import {
  apple,
  banana,
  coconut,
  mangoes,
  orange,
  passion_fruit,
  pear,
  pineaple,
  Beans,
  corn,
  rice,
  sorghum,
  wheat,
  bitter_leaf,
  cabbage,
  carrots,
  garden_egg,
  green_beans,
  lettuce,
  okra,
  onions,
  pepper,
  spinach,
  bees,
  cows,
  fish,
  poultry,
  rabbits,
  sheep,
  cassava,
  ginger,
  Potatoes,
  tumeric,
  tomatoe,


} from "../assets/images/index";

import "./style.css";

// =================== NavBarList Start here ====================
export const navBarList = [
  {
    _id: 1001,
    title: "Home",
    link: "/",
  },
  {
    _id: 1002,
    title: "Market",
    link: "/shop",
  },
  {
    _id: 1003,
    title: "About",
    link: "/about",
  },
  {
    _id: 1004,
    title: "Contact",
    link: "contact",
  }
];
// =================== NavBarList End here ======================

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: "1",
    img: apple,
    productName: "Apple",
    price: "3,500",
    badge: true,
    brand: "Pantum",
    des: "Apple Cultivated in the heart of Buea",
    cat: "Fruits"
  },
  {
    _id: "2",
    img: banana,
    productName: "Banana",
    price: "1,300",
    badge: true,
    brand: "Pantum",
    des: "Sweet banana",
    cat: "Fruits",
  },

  {
    _id: "3",
    img: coconut,
    productName: "Coconut",
    price: "9,000",
    badge: true,
    brand: "Pantum",
    des: "Coconut",
    cat: "Fruits"
  },

  {
    _id: "4",
    img: mangoes,
    productName: "Mangoes",
    price: "4,000",
    badge: true,
    brand: "Pantum",
    des: " Mangoes.........",
    cat: "Fruits",
  },

  {
    _id: "5",
    img: orange,
    productName: "Orange",
    price: "9,000",
    badge: true,
    brand: "Pantum",
    des: "Basket of fresh Oranges",
    cat: "Fruits",  
  },

  {
    _id: "6",
    img: passion_fruit,
    productName: "Passion Fruit",
    price: "1,000",
    badge: true,
    des: "Passion fruit......",
    cat: "Fruits",
  },

  {
    _id: "7",
    img: pear,
    productName: "Pear",
    price: "2,000",
    badge: true,
    des: ".......",
    cat: "Fruits",
  },

  {
    _id: "8",
    img: pineaple,
    productName: "Pineaple",
    price: "1,500",
    badge: true,
    des: ".........",
    cat: "Fruits",
  },
  {
    _id: "9",
    img: Beans,
    productName: "Beans",
    price: "9,000",
    badge: true,
    des: ".....",
    cat: "Grains",
  },
  {
    _id: "10",
    img: corn,
    productName: "Corn",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Grains",
  },
  {
    _id: "11",
    img: rice,
    productName: "Rice",
    price: "15,000",
    badge: true,
    des: ".....",
    cat: "Grains",
  },{
    _id: "12",
    img: sorghum,
    productName: "Sorghum",
    price: "8,000",
    badge: true,
    des: ".....",
    cat: "Grains",
  },{
    _id: "13",
    img: wheat,
    productName: "Wheat",
    price: "15,000",
    badge: true,
    des: ".....",
    cat: "Grains",
  },
  {
    _id: "14",
    img: bitter_leaf,
    productName: "Bitter Leaf",
    price: "10,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",

  },{
    _id: "15",
    img: cabbage,
    productName: " cabbage",
    price: "10,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",

  },
  {
    _id: "16",
    img: carrots,
    productName: " Carrots",
    price: "10,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },
  {
    _id: "18",
    img: garden_egg,
    productName: " Garden Egg",
    price: "3,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },
  {
    _id: "19",
    img: green_beans,
    productName: " Green Beans",
    price: "2,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },
  {
    _id: "20",
    img: lettuce,
    productName: " Lettuce",
    price: "5,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },{
    _id: "21",
    img: okra,
    productName: " Okra",
    price: "3,500",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },{
    _id: "22",
    img: onions,
    productName: " Onions",
    price: "5,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },{
    _id: "23",
    img: pepper,
    productName: " Pepper",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },
  {
    _id: "24",
    img: spinach,
    productName: " Spinach",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },{
    _id: "35",
    img: tomatoe,
    productName: " Tomatoes",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Vegetable",
  },
  {
    _id: "25",
    img: bees,
    productName: " Bees",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },
  {
    _id: "26",
    img: cows,
    productName: " Cows",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },
  {
    _id: "27",
    img: fish,
    productName: " Fish",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },
  {
    _id: "28",
    img: poultry,
    productName: " Fouls",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },
  {
    _id: "29",
    img: rabbits,
    productName: " Rabbits",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },
  {
    _id: "30",
    img: sheep,
    productName: " Sheep",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "LiveStock",
  },{
    _id: "31",
    img: cassava,
    productName: " Cassava",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Roots",
  },{
    _id: "32",
    img: ginger,
    productName: " Ginger",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Roots",
  },{
    _id: "33",
    img: Potatoes,
    productName: " Potatoes",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Roots",
  },{
    _id: "34",
    img: tumeric,
    productName: " Tumeric",
    price: "4,000",
    badge: true,
    des: ".....",
    cat: "Roots",
  },
  
];

export const baseURL = "http://localhost:8000"
export const USER_ID = sessionStorage.getItem('userID')
export const driver_ID = sessionStorage.getItem('driverId')
export const admin_ID = sessionStorage.getItem('adminID')
export const MSG_VAR = {
  ERROR: 'error',
  OK: 'OK'
}
export const USER_ROLE = {
   CLIENT: "Client",
   FARMER: "Farmer",
   DRIVER:'Driver',
   CONSULTANT: "Consultant",
   ADMIN: "Admin",
}
